### PR TITLE
Range Slider Implementation

### PR DESCRIPTION
**Pull request by Rodhlann**
Not all wired up, ended up being pretty busy this weekend.

### CODE REVIEW

**Comment by TillaTheHun0** [comment]
LGTM. In the future we might add the settings to a service, and have that pull default settings from firebase and also persist any changes made via profile page.

**Comment by TillaTheHun0** [comment]
before we merge this, can you prune all of that extra stuff besides the bower install and update the bower dependencies?

**Comment by bmykietka** [comment]
:thumbsup:

**Comment by TillaTheHun0** [comment]
merging weeeee

**Comment by bmykietka** [comment]
Sorry should have seconded your suggestion to prune thangs.

**Comment by TillaTheHun0** [comment]
I goofed. I thought reverting would reopen this one, but it just created a new one. Pepper is going to just fix up everything and submit another PR from that branch.

**Pull request merged**
